name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 converter:
    name: Run converter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: 'resources.yml'
          from: 'yaml'
          to: 'json'
      - name: Print json2yaml result
        run: echo "${{ steps.json2yaml.outputs.data }}"
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
         url: 'https://webhook.site/1ea300dd-dc8f-4bd4-a53d-e219ee647d65'
         method: 'POST'
         data:  ${{ steps.json2yaml.outputs.data }}

