name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convertandsend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: YAML/JSON/XML Converter Action
      uses: fabasoad/yaml-json-xml-converter-action@v1.0.12
      with:
    # Path to the file
        path: 'resources.yml'
    # Format of a file. Possible values: json, xml, yaml.
        from: 'yaml'
    # Format of a file as a result. Possible values: json, xml, yaml.
        to: 'json'
    - name: Print json2yaml result
      run: echo "${{ steps.json2yaml.outputs.data }}"
      

