name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      name: Get List of changed files 
      id: filter
      with:
        list-files: json
        filters: |
         changed:
          - '**' 
    outputs:
      listOfChangedFiles : ${{ steps.filter.outputs.changed_files }}
      
 show-result:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: print changes
        run : echo "${{ needs.filter.outputs.listOfChangedFiles}}""
    
    


