name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout file changes
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: json
        filters: |
         changed:
          - '**'
    
    - name: Lint Markdown
      uses: johndoe/some-action@v1
      with:
       files: ${{ steps.filter.outputs.changed_files }}
    
    


