name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: ./
    
jobs:
 filter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      name: Get List of changed files 
      id: filter
      with:
        list-files: json
        filters: |
         changed:
          - '*.yml' 
    outputs:
      listOfChangedFiles : ${{ steps.filter.outputs.changed_files }}
      
 show-result:
    needs:  filter
    runs-on: ubuntu-latest
    steps:
      - name: print changes
        id : show-result
        run : echo "${{ needs.filter.outputs.listOfChangedFiles}}"
    outputs:
      changedFiles: ${{ needs.filter.outputs.listOfChangedFiles}}
 
 convertAndSend:
    needs: show-result
    runs-on: ubuntu-latest
    env:
      FILES: ${{ needs.show-result.outputs.changedFiles}}
    steps:
      - name: Convert yaml to json and send
        id: convertAndSend
        run: |
           $FILES | jq
          

       
  
    
    


