name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  changedfilesconverter:
    runs-on: ubuntu-latest
    steps:
     - name: Verify Changed files
       uses: tj-actions/verify-changed-files@v7.2
       id: verify-changed-files
       with:
        files: |
          .(yml)$
          
     - name: Run step only when files change
       if: steps.verify-changed-files.outputs.files_changed == 'true'
       run: |
          echo "Changed files: ${{ steps.verify_changed_files.outputs.changed_files }}"
    
  converter:
   name: Run converter
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: 'resources.yml'
          from: 'yaml'
          to: 'json'
      - name: Print json2yaml result
        run: echo "${{ steps.json2yaml.outputs.data }}"
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
         url: 'https://webhook.site/1ea300dd-dc8f-4bd4-a53d-e219ee647d65'
         method: 'POST'
         data:  ${{ steps.json2yaml.outputs.data }}

