name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: ./
    
jobs:
 filter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      name: Get List of changed files 
      id: filter
      with:
        list-files: json
        filters: |
         changed:
          - '**' 
    - name: Print Result
      id: printResult
      run: |
       for f in ${{ steps.filter.outputs.changed_files }};
       do
        echo $f
       done
     
       
  
    
    


